### PR TITLE
Add revisions documentation - Issue #196

### PR DESCRIPTION
**Pull request by AdamWorley**
Pull request that resolves issue #196

### CODE REVIEW

**Review by davidmehren — CHANGES_REQUESTED** [review]
Thank you for your contribution!
Please use "note" instead of "file", as we already use the "note" wording in the rest of the features page.
Please also [sign your work](https://github.com/codimd/server/blob/master/CONTRIBUTING.md#sign-your-work). :smiley:

**Comment by AdamWorley** [comment]
Sorry for the mess of commits I was having trouble with gpg4win. 
I hope everything is all good now

**Comment by ErikMichelson** [comment]
I've got some minor remarks:
1. It seems you signed-off some other commits that are already merged to master. Let's get that fixed prior merge. If you need further assistance for this, let us know.
2. The new section about revisions is on the same level as "Workspace", "View" or "Edit". I would rather move the revision section into the workspace-section. My suggestion would be to place it just below the information about note-permissions.

**Comment by AdamWorley** [comment]
Sure I'll move the revision section to under permissions and above embed note.

I've not used commit signing before so I'm not sure how to go about fixing the already merged commits, so any instructions would be great, thanks!

**Comment by davidmehren** [comment]
You should be able to do the following:
```
# Add a new remote upstream with a clean history
git remote add upstream git@github.com:codimd/server.git
# Fetch branches from new remote
git fetch upstream
# Rebase your branch on master
git rebase upstream/master
# Force push to your fork
git push --force
```
After that this PR should only contain your commits

**Comment by SISheogorath** [comment]
Great work!

**Comment by AdamWorley** [comment]
Thank you @davidmehren for the instructions, just done them now so all should be good

**Pull request merged**
