### PR TITLE
Dropping CDN support

### PR DESCRIPTION
**Pull request by ErikMichelson**
Removing the CDN support as stated in #175.

Help wanted: There's only one reference to the CDNs yet that resides in the `html.hbs` for the HTML export. I don't know which local files I should add there as replacement.

### CODE REVIEW

**Comment by SISheogorath** [comment]
I think we are missing a webpack output for the html.hbs. In general we can probably have a look at the webpack.js in order to reduce the complexity of it. But I think the webpack part is out of scope of this issue.

It would be great when @davidmehren could have a look at the webpack part :)

**Comment by ErikMichelson** [comment]
Even if the webpack output for html.hbs is still using some CDN sources, could this be merged prior to 1.6-release as a first step?

**Comment by SISheogorath** [comment]
Personally I would like to avoid this being done half-way through. I'll may find some time to fix this completely during this week.

**Comment by davidmehren** [comment]
Closing, we are redoing a CDN-less frontend anyway :smiley:

**Pull request closed without merging**
