### PR TITLE
Provide documentation for configuration with Keycloak

### PR DESCRIPTION
**Pull request by boardfish**
Admittedly a little tired today, so I doubt this is up to scratch just yet. I'd recommend spinning up an instance of Keycloak locally using the `jboss/keycloak` container, and trying to run through it that way.

I'll make this as a draft for now so that I can add screenshots and whatnot. I'd appreciate any feedback you have to offer, especially from those who haven't touched Keycloak before.

### CODE REVIEW

**Comment by ccoenen** [comment]
Oh, wow! I'll take a look tonight!

**Comment by SISheogorath** [comment]
@boardfish, could you sign-off your commits? Please check https://github.com/codimd/server/blob/master/CONTRIBUTING.md#sign-your-work for details.

In order to achieve this in this PR, you can simply run `git rebase -s master && git push --force-with-lease=59c26d1962e9a22c53c6fba2a055929fe22f2bb2` :slightly_smiling_face:

**Comment by boardfish** [comment]
@SISheogorath Seems to be passing now – is this good to go?

**Comment by SISheogorath** [comment]
Great! Let's get this merged :) Thanks a lot!

**Pull request merged**
