### PR TITLE
WIP: Start 2.0 development

### PR DESCRIPTION
**Pull request by SISheogorath**
This PR will be the sum up of the 2.0 Release. Please file your changes against the `release/2.0.x` branch.

I started with @davidmehren's work on TypeScript as a nice base which was rebase to the latest master. Let's add a little To-Do-List:

- [ ] Further migration to TypeScript (@davidmehren maybe?)
- [ ] Move notes to subdirectory (?)
- [ ] Rebase and rework configs from the ground up (@SISheogorath)
- [ ] Add basic user profile (@ccoenen maybe?)
- [ ] Rework embedding content (?)

Further ideas for 2.0 should be shared [with the community forum](https://community.codimd.org/t/your-plans-for-version-2-0/81). Please help us by participating and making 2.0 rock-solid :)

### CODE REVIEW

**Comment by davidmehren** [comment]
So now that Travis is green, should we move forward with merging this into `master`?

**Comment by SISheogorath** [comment]
Do we want to deploy this to the demo instance? do you think it's stable enough for that?

**Comment by davidmehren** [comment]
We tested the last PR and did not notice anything obviously broken :D
Of course there might still be subtle bugs somewhere, which is why I would appreciate more users using this code.
On the other hand I'm not sure if users of the demo instance care enough to report any bugs they might encounter. Maybe we should label the demo instance as "this is running development code, please expect and report bugs"?

**Comment by ErikMichelson** [comment]
Maybe we want to run a separate dev-demo-instance with this?

**Comment by tilmanvatteroth-quinscape** [comment]
I agree with @ErikMichelson. Most people expect demo.codimd.org to be stable, because they want to test the latest stable version or because they are using it in production. So I won't deploy any dev version there. But dev.codimd.org (with a little ad on demo.codimd.org) sounds gut.

**Comment by mrdrogdrog** [comment]
I agree with @ErikMichelson. Most people expect demo.codimd.org to be stable, because they want to test the latest stable version or because they are using it in production. So I won't deploy any dev version there. But dev.codimd.org (with a little ad on demo.codimd.org) sounds gut.

**Comment by SISheogorath** [comment]
Well, I mean that makes the answer quite clear, we don't consider this version stable enough yet to be merged into master.

I'll setup a dev instance that will run the latest release/2.0.x version this evening. As soon as we consider it stable enough, we should move it towards the demo instance. Because that's the main purpose of the demo instance: running the latest master release to provide us with feedback.

**Comment by davidmehren** [comment]
I doubt that a separate dev-instance that noone uses will be helpful, precisely because most users use the normal one.

> we don't consider this version stable enough yet to be merged into master.

That really depends on the merge criteria for `master`. This code is obviously not release-ready, but should not have any glaring features broken. So "runs well, bugs probable" is probably the best description.

As we don't (yet?) have any frontend-tests, running this on an instance with some users is probably the best option. I mean we don't have any uptime or retention guarantees for the demo instance, have we?

**Comment by SISheogorath** [comment]
We don't. The demo instance has this name in order to hint people to the idea that data might disappear at any time. Not that we intend to do that, but that's the message.

But the idea should be to get the master and have something that runs and looks like CodiMD :D

We only support stable versions, so from that perspective that's all clear. But actually brings me to one point: Do we want to release a 1.6.1 first, that contains the latest changes from master, before we obliterate them by merging this branch?

**Comment by davidmehren** [comment]
Fully agree on 1.6.1, I opened #387 to track that.

**Comment by InnayTool** [comment]
I think we should close this PR because we don't want to push this to master. For now we use the develop branch for developing release 2.0. The release/2.0.X branch will be merged completely to the develop branch and to reduce confusion we should delete release/2.0.X.

**Comment by InnayTool** [comment]
I close this PR because of the reasons stated above.

**Pull request closed without merging**
