### PR TITLE
Fix crash in lutim integration

### PR DESCRIPTION
**Pull request by gramakri**
See https://github.com/Dylanderv/node-lutim/blob/master/lib/lutim.js#L105

### CODE REVIEW

**Comment by SISheogorath** [comment]
Good catch! could you please sign-off your commit?

https://github.com/codimd/server/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by gramakri** [comment]
@SISheogorath Will do, later today! Despite the fix, I haven't gotten lutim to work. still debugging that

**Comment by SISheogorath** [comment]
If you feel like you need more help or at least look for more interactive support, don't forget to join our community channel: https://riot.im/app/#/room/#codimd:matrix.org

**Comment by gramakri** [comment]
I have added the DCO

**Pull request merged**
