### PR TITLE
Remove edit URL from read-only note

### PR DESCRIPTION
**Pull request by ritesh-pandey**
Remove edit URL from read-only note

Signed-off-by: Ritesh Pandey <ritpan2003@gmail.com>

### CODE REVIEW

**Comment by ErikMichelson** [comment]
If a note is published, it's url will be the short-id of the note. But if FreeURL mode is enabled and the note has an alias set, the published url equals to the alias. In this case someone already has the link to the edit page, so the removal of the edit link is not enough. Therefore we should maybe change the publish function so that it always redirects to the short-id of the note.

**Comment by ErikMichelson** [comment]
One additional thing: The route `/s/example-note/edit` should also be removed otherwise this whole change would be useless.

see [here](https://github.com/codimd/server/blob/master/lib/response.js#L454-L456) and [here](https://github.com/codimd/server/blob/master/lib/response.js#L440-L442)

**Comment by SISheogorath** [comment]
I actually considered this more of a UX and cosmetic than a functional change.

This link shouldn't be remove entirely. But when the user has no edit access to the note.

Removing the `/s/<shortid>/edit` endpoint doesn't make sense, since you can also access the note using /<shortid>`.

As written in the corresponding issue, please make it a conditional, not just a removal of code.

**Comment by ritesh-pandey** [comment]
I am new to this project. Hence I am unable to understand the scope of this feature. This is requiring multiple commits. I should have used a draft PR here. But the feature to convert a PR to draft PR is not available yet. Please suggest how to take this ahead.

**Comment by ErikMichelson** [comment]
Maybe we should overthink the whole permission system before finalizing this PR/issue. There are great ideas of new concepts like groups or extensive tagging. These changes need to result in a change of our current permission system. Therefore it would be double work if we implement the conditions here now, or?

**Comment by davidmehren** [comment]
As we are planning to overthink the permissions system in the 2.0 release, I'm closing this for now.

**Pull request closed without merging**
