### PR TITLE
fix(oauth2): add state parameter

### PR DESCRIPTION
**Pull request by haslersn**
This is a port of: https://github.com/hackmdio/codimd/pull/1512

### CODE REVIEW

**Comment by davidmehren** [comment]
In #407 (merged to `release/2.0.x`) the `state` parameter was always set to `true`. Do you see any situation where someone might want to disable sending the state?

**Comment by haslersn** [comment]
No, I don' see any situation where someone might want to disable it. I was not aware of #407. I created this PR, because my CodiMD (I think version 1.6.0) didn't work with ORY Hydra.

**Comment by haslersn** [comment]
Why isn't #407 in the master branch?

**Comment by davidmehren** [comment]
`master` contains (stable) code that will go into the next point release (probably 1.7). `release/2.0.x` as well as `develop` contain unstable code that will become the 2.0 release in the future.

As we already merged the same feature with `state` hardcoded to `true`, I'm open to either doing that here or at least defaulting to `true` instead of `undefined`.

**Comment by haslersn** [comment]
I think that #407 should be considered as a bugfix and should be backported as far as you backport stuff. That is, it should definitely land in 1.7.

This PR on the other hand can be closed, except somebody else needs it. I don't need it.

**Pull request closed without merging**
