### PR TITLE
Config: Return String Instead Of Buffer For Docker Secrets

### PR DESCRIPTION
**Pull request by dargmuesli**
Prevents "TypeError: Cannot freeze array buffer views with elements".

### CODE REVIEW

**Comment by SISheogorath** [comment]
We might need another function call here: https://nodejs.org/api/all.html#fs_fs_readfilesync_path_options

**Comment by dargmuesli** [comment]
Ah yes, sure. I never really worked with node before, just for fixes like this :)

**Comment by SISheogorath** [comment]
For that you do a great job 👍🏼

**Comment by dargmuesli** [comment]
You do a great job too with giving a direction to work to with links to the documentation and not just giving the solution! That's how one learns.

**Pull request merged**
