### PR TITLE
Slightly improve documentation

### PR DESCRIPTION
**Pull request by Fonata**
Feedback is very welcome.

### CODE REVIEW

**Comment by ccoenen** [comment]
Very welcome changes. Very good indeed. There's one other file that might need a little love, too: the configuration via environment variables:

https://github.com/codimd/server/blob/9c1665ae5bf3cf38210ffd862d10de9b13bfacdd/docs/configuration-env-vars.md

would you like to take a look at that, too? (it's totally fine if you do not have time for that, I just thought I'd ask)

**Comment by Fonata** [comment]
@ccoenen Thanks for your feedback. Yes, I'll check env documentation, too.

I'll add a message once I think I'm done.

**Comment by Fonata** [comment]
I've finished my work on ``configuration-env-vars.md``. 

This PR is now ready for review. I don't plan to add more commits unless requested by the reviewer(s).

**Comment by Fonata** [comment]
Thanks for the feedback ☺️ 

I don't plan to update the Gravatar section soon, so I [created a separate issue #153](https://github.com/codimd/server/issues/153) to unblock this PR from getting merged.

**Pull request merged**
