### PR TITLE
Add note about renaming

### PR DESCRIPTION
**Pull request by SISheogorath**
To make it more obvious for people, a note in the README as recommended
by @danyork seems like a good idea.

Signed-off-by: Sheogorath <sheogorath@shivering-isles.com>

### CODE REVIEW

**Comment by DerMolly** [comment]
maybe we should mention that this rename will happen in 1.6.1?

**Comment by SISheogorath** [comment]
I think that's something people will notice :wink:

**Comment by SuperSandro2000** [comment]
I would put the note in the first text line below the badges or make it bold. Right now you could easily miss it if you revisit the readme and don't read everything twice.

**Comment by davidmehren** [comment]
I also think we should at least make the note bold, if not move it directly below the heading.

**Comment by SISheogorath** [comment]
@davidmehren done

**Comment by SISheogorath** [comment]
I think moving it more up doesn't necessarily help. People will get it at latest when the renaming is happening. Otherwise it's just a beforehand information anyway.

**Pull request merged**
