### PR TITLE
add help about note deletion in features.md

### PR DESCRIPTION
**Pull request by naimo**

### CODE REVIEW

**Comment by SISheogorath** [comment]
Hey, great to see you contribution :) Would be great if you could rebase them so your change is just one commit we need to merge.

To do this, checkout a new branch, rebase your changes interactively and remove all commits that are not related to your intended change.

1. `git checkout -b feature/document-deletion`
2. `git rebase -i upstream/master`
3. `git --set-upstream origin push`

Then you might need to recreate the PR. Hope it's not too much hassle, if anything is not clear, feel free to ask :)

**Comment by naimo** [comment]
Should be better now, thanks for the guidance

**Comment by naimo** [comment]
Arg I rebased on master, not release/2.0.x

**Comment by SISheogorath** [comment]
Great! Thanks for your contribution!

**Pull request merged**
