### PR TITLE
[DOC] Use `npm start`, not `yarn start` to start

### PR DESCRIPTION
**Pull request by bluehood**
`yarn start --production` ignores the `--production` flag,
`npm start --production` does not.

### CODE REVIEW

**Comment by bluehood** [comment]
Resolved conflicts, ready to merge

**Comment by ccoenen** [comment]
I know this was already merged, but shouldn't we also update

https://github.com/codimd/server/blob/313eb74ed697c5260df9293b1aefe3695cf65a5a/bin/setup

at the same time? If we stop using yarn (which I'm perfectly fine with!) we should also remove it from the setup script.

**Comment by bluehood** [comment]
I can't comment on dropping yarn altogether. There are still calls to yarn in the manual setup instructions. The PR only changed `yarn start` to `npm start` because otherwise the `--production` flag is ignored.

This might very well be a bug in yarn that they will fix in a next release, I don't know.

**Comment by SISheogorath** [comment]
I don't think we want to remove yarn, but just use npm for for the production start (since in yarn it simply doesn't work as with npm). When recently someone went through all files and replaced npm with yarn, it was unnoticed that `npm start --production` is fundamentally different from `yarn start --production`.

**Comment by ccoenen** [comment]
ok, got it :-)

**Pull request merged**
