### PR TITLE
WIP: Public API v2.0

### PR DESCRIPTION
**Pull request by DerMolly**

### CODE REVIEW

**Comment by DerMolly** [comment]
the openapi spec is currently unfinished. At least the following things need to be done
- [ ] history routes
- [ ] auth routes except email

**Comment by DerMolly** [comment]
We started a document on demo.codimd.org to track the todos with multiple people quickly
https://demo.codimd.org/ODakLc2MQkyyFc_Xmb53sg?both

**Comment by InnayTool** [comment]
I've re-based this PR on the develop branch because now I can edit it more easily when switching from code to docs and vice versa. I think we should close this PR and come to a more iterative way of developing the API and maybe open more PRs. In favour of this we should delete the release/2.0.X branch to reduce confusion.

**Comment by davidmehren** [comment]
This was merged into `develop`, let's close here.

**Pull request closed without merging**
