### PR TITLE
Anonymous views

### PR DESCRIPTION
**Pull request by SISheogorath**
Continuing @hakoai's work from https://github.com/hackmdio/codimd/pull/1152.

(We will close this PR in favor of one by the original author)

### CODE REVIEW

**Comment by clvs7-gh** [comment]
Hello.

Do you have any update on this?
hackmdio's one seems already merged. I think it is safe to merge.

**Comment by SISheogorath** [comment]
To be honest I'm not sure if we really want to do this. I see the reason why this might be useful, but I'm not really sure about the name of this option. I would prefer to put some time and effort into doing this right instead of merging this half-way through PR .-.

**Comment by davidmehren** [comment]
If the concept still needs discussion, we should probably move this to an issue? This seems related to [the other](https://github.com/codimd/server/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afeature%3Apermissions) permission issues.

**Comment by davidmehren** [comment]
Closing, as this got pretty stale and we are developing a new permissions system anyway with 2.0.

**Pull request closed without merging**
